### ISSUE TITLE
EMFILE crash

### ISSUE THREAD

**Issue by dominictarr** [socketsupply/introducer#8]
Leaving my phone running, then restarting the laptop several times, eventually it gets an EMFILE crash.
this is because it's doing a birthday paradox and that means the phone opens 256 ports each time.

The error means "maximum files" hmm now that I think of it, is it closing anything?

Also each BDP attempt it opens another 256 files, when it could actually just reuse the same ports.

There have been no complaints of this in dogfood... but I think it ought to have happened? does socket-sdk produce this error? @heapwolf @jwerle ?

**Comment by heapwolf** [comment]
I had this error too on macOS, I fixed it by changing the default ulimit that is requested by the app. It's possible we need to do something similar for linux. The other issue was that we weren't garbage collecting the file descriptors, we are now though, and that might have fixed this.

**Comment by dominictarr** [comment]
a better solution is just not open that many files. the hard side of BDP needs to open 256 ports, but they can use the same ports for the next connection.
